DROP TABLE IF EXISTS STAFFS;
CREATE TABLE STAFFS (
  UUID varchar(50) DEFAULT '',
  STAFF_ID varchar(50) DEFAULT '',
  NAME varchar(50) DEFAULT '',
  SEX char(1) DEFAULT '',
  BIRTHDATE date DEFAULT '',
  ADDRESS varchar(50) DEFAULT '',
  FIRST_DEPARTMENT varchar(50) DEFAULT '',
  SECOND_DEPARTMENT varchar(50) DEFAULT '',
  THIRD_DEPARTMENT varchar(50) DEFAULT ''
);